### ISSUE TITLE
freeswitch broken in buildbot

### ISSUE THREAD

**Issue by champtar** [openwrt/telephony#10]
Hi
An issue was open in package feed for freeswitch (openwrt/packages#630)
see also
http://buildbot.openwrt.org:8010/broken_packages/ar71xx/freeswitch/compile.txt

**Comment by plntyk** [comment]
Reason why it's broken: OpenSSL 1.0.2 detection

Upstream ticket: https://freeswitch.org/jira/browse/FS-7314

It is resolved upstream :
https://freeswitch.org/stash/projects/FS/repos/freeswitch/commits/320d2eae5253f2a5c7f440e9291d4cc3fab7e3d2

**Comment by BlueMax** [comment]
I get a similar error like in the referenced issue #630 above (after including the upstream patch):
> Checking for Networking support...
checking for in_addr in netinet/in.h... yes
checking if fd == socket on this platform... yes
checking style of gethostbyname_r routine... glibc2
checking 3rd argument to the gethostbyname_r routines... char
checking if TCP_NODELAY setting is inherited from listening sockets... yes
checking if O_NONBLOCK setting is inherited from listening sockets... yes
checking whether TCP_NODELAY and TCP_CORK can both be enabled... configure: error: in `/home/bluemax/openwrt/trunk/build_dir/target-i386_i486_uClibc-0.9.33.2/freeswitch-1.5.15b/libs/apr':
configure: error: cannot run test program while cross compiling
See `config.log' for more details
configure: error: ./configure.gnu failed for libs/apr
make[2]: *** [/home/bluemax/openwrt/trunk/build_dir/target-i386_i486_uClibc-0.9.33.2/freeswitch-1.5.15b/.configured_yyyyyynynynnnynnyynynnyyynynynnnnnnnnnnnnnnnnnnyynnnnnnnynnnynnnnnynnnnnnnnnnnnnnynnnnnnnnnynnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnynnynnnnnnnnnnnynynnnnnnnnnnnnnnnyyyyyyyyy] Error 1
make[2]: Target `compile' not remade because of errors.
make[2]: Leaving directory `/home/bluemax/openwrt/trunk/feeds/telephony/net/freeswitch'
make[1]: *** [package/feeds/telephony/freeswitch/compile] Error 2
make[1]: Leaving directory `/home/bluemax/openwrt/trunk'
make: *** [package/feeds/telephony/freeswitch/compile] Error 2

**Comment by jslachta** [comment]
This should be fixed. Please reopen if this issue persists.

**Comment by sageahn** [comment]
I am trying to build x86 openwrt with Freeswitch and the same issue still persists.
During configure in libs/apr, the following error has occurred. this is weird that I was successful to build freeswitch for i.MX6 target but x86 failed.

Following are the log during make.
```
Checking for Networking support...
checking for in_addr in netinet/in.h... yes
checking if fd == socket on this platform... yes
checking style of gethostbyname_r routine... glibc2
checking 3rd argument to the gethostbyname_r routines... char
checking if TCP_NODELAY setting is inherited from listening sockets... yes
checking if O_NONBLOCK setting is inherited from listening sockets... yes
checking whether TCP_NODELAY and TCP_CORK can both be enabled... configure: error: in `/home/sage/work_owrt/owrt_vm/build_dir/target-i386_i486_uClibc-0.9.33.2/freeswitch-1.5.15b/libs/apr':
configure: error: cannot run test program while cross compiling
See `config.log' for more details
configure: error: ./configure.gnu failed for libs/apr
make[3]: *** [/home/sage/work_owrt/owrt_vm/build_dir/target-i386_i486_uClibc-0.9.33.2/freeswitch-1.5.15b/.configured_yyyyyynnnynnnynnyynynnyyynynynnnnnnnnnnnnnnnnnnyynnnnnnnynnnynnnnnynnnnnnnnnnnnnnynnnnnnnnnynnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnynnynnnnnnnnnnnynynnnnnnnnnnnnnnn] Error 1
make[3]: Leaving directory `/home/sage/work_owrt/owrt_vm/feeds/telephony/net/freeswitch'
make[2]: *** [package/feeds/telephony/freeswitch/compile] Error 2
make[2]: Leaving directory `/home/sage/work_owrt/owrt_vm'
make[1]: *** [/home/sage/work_owrt/owrt_vm/staging_dir/target-i386_i486_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/sage/work_owrt/owrt_vm'
make: *** [world] Error 2
sage@flo1:~/work_owrt/owrt_vm$
```

and belows are the autoconf log (config.log) in libs/apr
```
| #include <stdlib.h>
| #endif
|
|   int main(int argc, const char *const *argv) {
|
| int tmp = gethostbyname_r((const char *) 0, (struct hostent *) 0,
|                           (struct hostent_data *) 0);
|      return 0; }
configure:24060: result: char
configure:24072: checking if TCP_NODELAY setting is inherited from listening sockets
configure:24196: result: yes
configure:24205: checking if O_NONBLOCK setting is inherited from listening sockets
configure:24328: result: yes
configure:24337: checking whether TCP_NODELAY and TCP_CORK can both be enabled
configure:24343: error: in `/home/sage/work_owrt/owrt_vm/build_dir/target-i386_i486_uClibc-0.9.33.2/freeswitch-1.5.15b/libs/apr':
configure:24345: error: cannot run test program while cross compiling
See `config.log' for more details

## ---------------- ##
## Cache variables. ##
## ---------------- ##
```

**Comment by BlueMax** [comment]
That should be handled here https://github.com/openwrt/telephony/commit/882da949e78a0995423b8e1144109980b72c6029 (net/freeswitch/patches/libs-apr-configure_ac.patch) already. Maybe you're not on upstream?

I once reverted that patch (that was in combination with disabled APU_CHECK_DBD_MYSQL, APU_CHECK_DBD_SQLITE3, APU_CHECK_DBD_SQLITE2 as well - not implemented by Mazi Lo though) in favor of the already implemented ARM cross-compile overrides (here https://github.com/openwrt/telephony/pull/32).
I personally prefer the 2nd solution (ARM cross-compile overrides) but i guess he knows what he's doing...

**Comment by taeasy** [comment]
Checking for DSO...
checking for NSLinkModule... no
checking for shl_load in -ldld... no
checking for dlopen... yes
checking for dlsym... yes

Checking for Processes...
checking for waitpid... yes
checking for Variable Length Arrays... no
checking struct rlimit... no

Checking for Locking...
checking for semget... yes
checking for semctl... yes
checking for flock... yes
checking for semaphore.h... (cached) yes
checking OS.h usability... no
checking OS.h presence... no
checking for OS.h... no
checking for sem_close... yes
checking for sem_unlink... yes
checking for sem_post... yes
checking for sem_wait... yes
checking for create_sem... no
checking for working sem_open... no
checking for union semun in sys/sem.h... no
checking for LOCK_EX in sys/file.h... yes
checking for F_SETLK in fcntl.h... yes
checking for SEM_UNDO in sys/sem.h... yes
checking for POLLIN in poll.h sys/poll.h... yes
checking for PTHREAD_PROCESS_SHARED in pthread.h... yes
checking for pthread_mutexattr_setpshared... yes
checking for pthread_setschedparam in -lpthread... yes
checking for robust cross-process mutex support... configure: error: in `/home/main/lede/build_dir/target-x86_64_musl-1.1.15/freeswitch-1.7.0/libs/apr':
configure: error: cannot run test program while cross compiling
See `config.log' for more details
configure: WARNING: cache variable V_Package_freeswitch_mod_cv_postinst contains a newline
configure: WARNING: cache variable V_Package_freeswitch_mod_cv_prerm contains a newline
configure: error: ./configure.gnu failed for libs/apr
configure: WARNING: cache variable V_Package_freeswitch_mod_cv_postinst contains a newline
configure: WARNING: cache variable V_Package_freeswitch_mod_cv_prerm contains a newline
Makefile:909: recipe for target '/home/main/lede/build_dir/target-x86_64_musl-1.1.15/freeswitch-1.7.0/.configured_nyyyyyynnyynnyyynnyyyynyynnyyynyyyyyyynyyyynyyynynyynyyyynyyyyyyyyyyyyynyyyyynnynynyyynynynnyynynyyyyyyyynnnnyyyyynynnyyynyyyyynyyyyyyyyyyyyynnnynnyyyyyyyynnnnnnyyyyyyyynynyyyyyynyyyyyyyyyyn' failed
make[3]: *** [/home/main/lede/build_dir/target-x86_64_musl-1.1.15/freeswitch-1.7.0/.configured_nyyyyyynnyynnyyynnyyyynyynnyyynyyyyyyynyyyynyyynynyynyyyynyyyyyyyyyyyyynyyyyynnynynyyynynynnyynynyyyyyyyynnnnyyyyynynnyyynyyyyynyyyyyyyyyyyyynnnynnyyyyyyyynnnnnnyyyyyyyynynyyyyyynyyyyyyyyyyn] Error 1
make[3]: Leaving directory '/home/main/lede/feeds/telephony/net/freeswitch'
package/Makefile:127: recipe for target 'package/feeds/telephony/freeswitch/compile' failed
make[2]: *** [package/feeds/telephony/freeswitch/compile] Error 2
make[2]: Leaving directory '/home/main/lede'
package/Makefile:124: recipe for target '/home/main/lede/staging_dir/target-x86_64_musl-1.1.15/stamp/.package_compile' failed
make[1]: *** [/home/main/lede/staging_dir/target-x86_64_musl-1.1.15/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/main/lede'
/home/main/lede/include/toplevel.mk:194: recipe for target 'world' failed
make: *** [world] Error 2
main@debian:~/lede$

**Comment by micmac1** [comment]
Hello @champtar @plntyk @sageahn @BlueMax 

freeswitch-stable is a drop-in replacement for freeswitch. Can you please try freeswitch-stable (in trunk, snapshots available) and close this issue if all is well?

Regards,
Sebastian
